### ISSUE TITLE
Cannot find module 'NodObjC'

### ISSUE THREAD

**Issue by JonnyHeavey** [telerik/ios-sim-portable#50]
When I try to invoke any isim command (except help), I am seeing the following error message:

Cannot find module 'NodObjC'

I'm using the following:

node 0.12.9
npm 2.14.9
osx 10.11.2
xcode 7.2

**Comment by teobugslayer** [comment]
I have published the new version of ios-sim-portable on [npm](https://www.npmjs.com/package/ios-sim-portable). If you are using AppBuilder or NativeScript clients, you may manually update the dependency. Their next versions will depend on the fixed ios-sim-portable.
